name: Check code style with ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    env:
      MESSAGE: |
        Your code is not formatted!
        Please set up your development environment and run the formatting command.
        https://icalendar.readthedocs.io/en/stable/contribute/development.html#code-format
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . --group formatting
      - name: Run the ruff formatter to change files
        run: ruff format .
      - name: Fail if we detect any changes on the file system
        run: |
          git status
          if ! git diff --exit-code; then
            echo "$MESSAGE"
            exit 1;
          fi
      - name: Run ruff checks on the files
        run: |
          if ! ruff check; then
            echo "$MESSAGE"
            exit 1;
          fi
